[SERVICE]
    Flush            5
    Daemon           Off
    Log_Level        info
    Parsers_File     /opt/fluent-bit/etc/parsers.conf

[INPUT]
    Name             tail
    Path             ${LOG_PATH}/app.log
    Tag              app_logs
    Read_From_Head   False
    Refresh_Interval 5
    Skip_Empty_Lines On
    Parser           json

[OUTPUT]
    Name             loki
    Match            *
    Host             ${LOKI_HOST}
    Port             3100
    Labels           job=app_logs,app=order-service
    Line_Format      json
